### ISSUE TITLE
Render output in html

### ISSUE THREAD

**Issue by jpfairbanks** [cjhutto/bsd#1]
This package would be really useful as a web tool, but output is only accessible in a CSV would it be possible to extend https://github.com/cjhutto/bsd/blob/master/bs_detector/bias.py#L470 to include HTML output?

**Comment by cjhutto** [comment]
This certainly seems viable, but should it be a core part of BSD (the output is no longer only accessible as a CSV -- it can be accessed as either a single "bias score" (float that is returned from `compute_bias(statement)` as shown in the demo function) or more immediately as the raw feature data (python dictionary that is returned from `extract_bias_features(unicode(sentence_text, errors='ignore'))`).

**Comment by cjhutto** [comment]
Added capability to print output as TSV (tab separated values) formatted or as HTML formatted.  Does this satisfy?

**Comment by scottagt** [comment]
That's cool; it's giving the feature sub-scores; and can we add bias score too per sentence? What we're wanting to do with it is create unit-by-unit score outputs along with sub-scores. This goes towards that for the sentence level. I'd want to have it for paragraph-level and really any arbitrary unit that is given to it to process.

**Comment by jpfairbanks** [comment]
Looks good to me
