### ISSUE TITLE
Enabling travis

### ISSUE THREAD

**Issue by jpfairbanks** [cjhutto/bsd#11]
@cjhutto, Since I am not the owner of this repo, I can't enable travis CI. Can you do that? The alternative is to create an organization to hold a few repos like vader, bsd, and other related projects. Then Scott and I could help administer them.

**Comment by cjhutto** [comment]
I just started the process to sync with travis.  Will enable it for vader and bsd.

**Comment by cjhutto** [comment]
Synced this repo with Travis, and enabled the repo in Travis CI.  I see the .travis.yml already created for BSD (thanks @jpfairbanks ).  Travis should run a build on the next commit that is pushed...
