### ISSUE TITLE
opinion_rto repeats twice in modelkeys, also subj_weak_rto?

### ISSUE THREAD

**Issue by connieimdialog** [cjhutto/bsd#20]
hi, @cjhutto @jpfairbanks 
check out modelkeys = ['vader_sentiment',
      ***       'opinion_rto',
             'modality',
             'liwc_3pp_rto',
             'liwc_tent_rto',
             'liwc_achiev_rto',
             'partisan_rto',
             'liwc_work_rto',
             'presup_rto',
             'hedge_rto',
             'assertive_rto',
      ***       'opinion_rto']

The last field shouldn't be opinion_rto but i think subj_weak_rto which is no longer in this version of bias detector?
thanks!

**Comment by jpfairbanks** [comment]
git-bisect says that this was broken in f58fabd16f07 and correct in 52f62ba22fba.

That would be the following commit: 

```f58fabd16f07dfb6e3696f520fde3d150f76aba4
Author:     Hutto, CJ <cjhutto@gatech.edu>
AuthorDate: Tue Dec 26 10:14:26 2017 -0500
Commit:     Hutto, CJ <cjhutto@gatech.edu>
CommitDate: Tue Dec 26 10:14:26 2017 -0500

Parent:     e85fe13 Merge pull request #13 from cjhutto/server
Merged:     installing linting requirements
Containing: master

Major revision to features, lexicons, quote handling, training data/input text

Updated reference lexicons JSON to contain orthogonal / distinct lists
of words, terms, phrases.
Added, removed, modified, combined, features in "features dictionary"
used for predictions.
Added functionality to include considerations for quoted material.
Added new sentences from news to use as training data / input text.
```
which contains the following diff:

```diff
 
@@ -497,14 +446,12 @@ def compute_bias(sentence_text):
                 8.3551389 * features['liwc_3pp_rto'] +
                 4.5965115 * features['liwc_tent_rto'] +
                 5.737545 * features['liwc_achiev_rto'] +
-                5.6573254 * features['liwc_discr_rto'] +
-                -0.953181 * features['bias_rto'] +
+                -0.953181 * features['partisan_rto'] +
                 9.811681 * features['liwc_work_rto'] +
-                -16.6359498 * features['factive_rto'] +
+                -16.6359498 * features['presup_rto'] +
                 3.059548 * features['hedge_rto'] +
                 -3.5770891 * features['assertive_rto'] +
-                5.0959142 * features['subj_strong_rto'] +
-                4.872367 * features['subj_weak_rto'])
+                5.0959142 * features['opinion_rto'])
     return bs_score
```
@cjhutto, when you updated the coefficients, was this a simple typo? Is the correct coefficient `5.09` or `4.87`? Or something else?

**Comment by cjhutto** [comment]
@connieimdialog, @jpfairbanks:
    actually, you are both correct -- I'm looking at the code as checked in on GitHub, and the modelkeys (represented by the types of bias indicators aggregated in each of the lexicons) are not up to date/in sync with the latest bias model in my dev environment... I'll need to update and load the next version of bias.py and the correct lexicon set (which organizes opinion, strong subj, and weak subj into the same category representing the type of of bias called subjective "value" bias indicators).  Note that due to travel and other work commitments at the moment, it may be Wednesday before I get it up... (or, if the need is dire, I could stay up late tonight and at least get the main parts straightened out -- I can at the very least implement the multiple linear regression model, but I'm still working out how to translate SVM machine learning model (as used in R stats package 'caret') to executable python for the inline bias computation).

**Comment by connieimdialog** [comment]
hi @cjhutto thanks so much.    there is a strong need -- we are trying to present this with results for a joint project proposal, but **totally** understand that you are swamped.  if a correct mult. linear model is possible sooner later day/early tomorrow, but if it's only one more day until you get what you're hoping for...  anyhow, lmk what you think and are able to do.

**Comment by jpfairbanks** [comment]
@cjhutto can use the old model coefficient for now and use the new models when they are ready?

**Comment by cjhutto** [comment]
@connieimdialog, @jpfairbanks, @scottagt 
     I think I've straightened it out, or at least on my own host machine... 

I'm still writing up details, but here is a summary of how the (orthogonal) bias markers/features are organized:

**Lexical level indicators of bias in sentences:**
- presupposition markers
	-- reflects epistemological bias and presupposed truths; "leading" or suggesting a conclusion; endowment/shepherding bias; editorializing; indicators of framing bias
	-- includes: factive verbs, implicative verbs, asserting words, causation words,  coherence markers
- value laden language 
	-- injects a writer's own subjective values into the presentation of issues/facts; subjective opinion or positively/negatively loaded language; partial tone; sensationalism
	-- includes: VADER opinion lexicon, Subj weak, Subj strong, Wikipedia flagged words as NPOV-violation watch words, and degree modifiers that may reflect attempts at subtle sensationalism
- figurative language
	-- reflects non-neutral perspective bias; WP NPOV "puffery/peacock" language, editorializing; sensationalism
	-- implicit nature of figures of speech manipulates the opinion of the reader
	-- includes: English idioms, metaphors, metonymy, hyperbole, simile
- partisan language / contentious labels / one-sided terms
	-- reflects ideological bias and/or framing bias, and a non-neutral point of view
	-- includes, for example, consideration of phrases such as "terrorists" vs "freedom fighters" vs "rebels" vs "insurgents"...or "pro-choice" vs "pro-abortion" or "pro-life" vs "anti-abortion"
- self reference 
	-- may indicate personal thoughts rather than objective/unbiased (neutral) point of view
	-- uses LIWC list of self reference pronouns
- attribution 
	-- reflects possible (fundamental) attribution bias, actor-observer bias; ultimate attribution bias
	-- uses LIWC lists of third person pronouns, achievement words, work words 
- expressions of doubt, uncertainty, unsupported/vague attributions
	-- may reflect or imply inaccuracies, calling a statement's credibility into question 
	-- includes: LIWC tentative words, WP NPOV hedges/weasels

**Sentence level level indicators of bias in sentences:**
- Sentence length (word count)
- Flesch-Kincaid Grade Level
- Quote length (no. of words in quotation)
- Absolute value of VADER Sentiment (compound score)
- Modality (degree of certainty)
- Negative-Perspective (negativity/positivity bias; fading effect bias)

**Comment by connieimdialog** [comment]
thanks @cjhutto, checking it out now!

**Comment by connieimdialog** [comment]
actually, quick Q @cjhutto -- can you share what the p-values are for these features? do you have anything published w/r/t these results or is this currently in dev?  thanks!

**Comment by connieimdialog** [comment]
@cjhutto  oops, one more thing,  just confirming that the modelkeys should now be pointing to *counts* and not to *ratios* (like value_cnt instead of value_rto)?

**Comment by cjhutto** [comment]
@connieimdialog 
1. yes - these are currently all in dev, being written up now though for publication. p-values and other model statistics for the trained multiple linear regression model are below...

2. yes - this model uses word count (sentence length) in addition to the counts of feature occurances

```
	Call:
	lm(formula = .outcome ~ ., data = dat)

	Residuals:
		 Min       1Q   Median       3Q      Max 
	-1.50902 -0.50169 -0.08946  0.46715  1.93443 

	                 Estimate   Std. Error t value Pr(>|t|)    
	(Intercept)      0.844952   0.068159  12.397  < 2e-16 ***
	word_cnt        -0.015031   0.003612  -4.162 3.44e-05 ***
	vader_abs        0.055452   0.087178   0.636 0.524877    
	neg_persp        0.064741   0.039045   1.658 0.097627 .  
	certainty       -0.018446   0.061806  -0.298 0.765427    
	quote_length    -0.008512   0.003881  -2.193 0.028524 *  
	presup_cnt       0.048985   0.014079   3.479 0.000525 ***
	doubt_cnt        0.047783   0.034899   1.369 0.171274    
	partisan_cnt     0.028755   0.015699   1.832 0.067319 .  
	value_cnt        0.117819   0.012941   9.104  < 2e-16 ***
	figurative_cnt   0.269963   0.095018   2.841 0.004590 ** 
	attribution_cnt -0.041790   0.014378  -2.906 0.003740 ** 
	self_refer_cnt   0.129693   0.032812   3.953 8.30e-05 ***
	---
	Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

	Residual standard error: 0.6471 on 955 degrees of freedom
```

![var_imp](https://user-images.githubusercontent.com/1241440/37412177-cd072ab6-277a-11e8-82b2-e87270f8a66d.png)

**Comment by cjhutto** [comment]
Is this issue resolved and ready to be closed?

**Comment by connieimdialog** [comment]
hi @cjhutto , i am wondering if normalized_features should multiply not divide by the coefficients? 

or --  see attached example, i'm having trouble making meaningful interpretations about which factor has more impact on the bias_score, so could use some help with this!

[bias-2018-03-16-normalized.xlsx](https://github.com/cjhutto/bsd/files/1818898/bias-2018-03-16-normalized.xlsx)

**Comment by cjhutto** [comment]
@connieimdialog 
   Ok! 
So, it appears that the code is now working on the troublesome non-ASCII text?  Good...that was step 1.  
     I'll need to inspect the code for the normalization function (and wrap @jpfairbanks into the discussion, as I spoke to him over the phone and email about this process, but didn't do any testing or evaluation of that functionality).  My feeling is that simple division by the coefficient might not exactly give the kind of "impact" measure we are looking for... let me take a quick look at perhaps (instead) using the trick of taking the log after transforming all feature scores to be between 0 and 1 (should be easy -- most features are counts except for sentiment, negativity, and certainty)...

**Comment by cjhutto** [comment]
@connieimdialog 
   check the following - I think it might do what you are wanting. It normalizes using a sigmoid function method (specifically, via the top half of the [logistic function](https://en.wikipedia.org/wiki/Logistic_function))...this seems (to me) to make more sense that the existing normalization method:

![sample](https://user-images.githubusercontent.com/1241440/37543062-c2feeece-2936-11e8-96f2-e3ad9a60dc66.png)

Some things to note:
1. The bias scores all make really good sense to me... s3 is the most biased, followed by s4 and s1
2. Can't just multiply beta * feature value, because they are different units / scales. So have to Normalize first, then multiply the normed value * the appropriate regression coefficient (beta).
3. Using s1 as the example -- the "presup" and "partisan" features had the same values (both had 2 words counted), but because the regression coefficient for presupposition language markers is nearly double that of partisan language markers, the normalized impact of presup was almost twice that of partisan. Cool. Makes sense.
4. Same deal if we look at s2...see how many features in s2 all had a feature value of 1? But those features all had appropriately scaled "impact" because of normalizing and beta weight scaling...

Below is my sample script that generated the logistic normalization data in the above table:

```
# import the req'd methods from bias.py
from bias import compute_bias, extract_bias_features

# make a reference dictionary containing the multiple linear regression coefficients
mlrmdict = {  # 'intercept'      : 0.844952,
    'word_cnt': -0.01503,
    'vader_senti_abs': 0.055452,
    'neg_persp': 0.064741,
    'certainty': -0.01845,
    'quote_length': -0.00851,
    'presup_cnt': 0.048985,
    'doubt_cnt': 0.047783,
    'partisan_cnt': 0.028755,
    'value_cnt': 0.117819,
    'figurative_cnt': 0.269963,
    'attribution_cnt': -0.04179,
    'self_refer_cnt': 0.129693}

# calculate the (normalized) impact of each feature for a given sentence using the 
#    top half of the logistic function sigmoid
def measure_feature_impact(sentence):
    impact_dict = {}
    e = 2.7182818284590452353602874713527  # e constant (Euler's number)
    ebf = extract_bias_features(sentence)
    for k in mlrmdict.keys():
        impact_dict[k] = (2 * (1 / (1 + e**(-abs(ebf[k])))) - 1) * abs(mlrmdict[k]) * 100
    return impact_dict

# make a quick printout to the console to see the data
def detailed_bias_analysis(sentence_list):
    for s in sentence_list:
        b = compute_bias(s)
        imp = measure_feature_impact(s)
        imp_str = "\n\t".join([str((k, round(imp[k], 3))) for k in imp])
        print ("{}\n\tbias: {}\n\t{}".format(s, b, imp_str))

# example using a list of realistic sample sentences
sentences = [
    """British ministers including Theresa May and Philip Hammond have made hair-raising 
       claims about the dangers of migrants entering the country.""",
    "But do the facts bear them out?",
    """When you're facing the world's biggest refugee crisis since the second world war, it 
       helps to have a sober debate about how to respond.""",
    """But to do that, you need facts and data - two things that the British migration debate  
        has lacked this summer.""",
    """Theresa May got the ball rolling in May, when she claimed on Radio 4 that the vast 
       majority of migrants to Europe are Africans travelling for economic reasons."""]

# do the sentence by sentence bias analysis and print the bias score and feature impacts
detailed_bias_analysis(sentences)
```

**Comment by connieimdialog** [comment]
thanks for this @cjhutto diving in today

**Comment by connieimdialog** [comment]
actually, we're willing to give this a go @cjhutto  -- could you check in the function?

**Comment by cjhutto** [comment]
> could you check in the function

Done!

**Comment by connieimdialog** [comment]
hey @cjhutto i think there's some syntax errors in the code. the test cases aren't passing. we can try again tomorrow to debug but in case you find them first..

**Comment by connieimdialog** [comment]
hiya, we have something working so can consider this closed @cjhutto @jpfairbanks @scottagt.  i'll share some results/interpretations with you for your thoughts soon.

in the meanwhile, i've condensed some of the above in the update to this page: https://newsframes.globalvoices.org/tools/using-bias-detector-in-newsframes/  feedback/thoughts welcome.

**Comment by jpfairbanks** [comment]
> This functionality, a collaboration with Georgia Tech's 
> Behavioral Modeling and Computational Social Systems

I think this should end with a noun like "group" or "lab". Erica 
can confirm, but I think "Georgia Tech Research Institute 
Behavioral Modeling and Computational Social Systems Group" would 
be the full name of our organization group.

> Human interpretation is required to affirm or reject the 
> suggestions made by these algorithms.

I think this should emphasize "definitively affirm or reject" 
otherwise it sounds like the software is totally untrustworthy.

> Self Reference – may indicate personal thoughts rather than an 
> objective/unbiased point of view. Includes: self-referential 
> pronouns.

Maybe an example of writing like, "I got fired from X, this my 
story" would be appropriate for this list item.


connieimdialog writes:

**Comment by jpfairbanks** [comment]
Also a direct reference to the article in addition to the github would be helpful. 

> Hutto, C.J. (2015). Computationally Detecting and Quantifying the Degree of Bias in Sentence-Level Text of News Stories. Second International Conference on Human and Social Analytics (HUSO-15). Barcelona, Spain 2015.
