### ISSUE TITLE
Shipping ref_lexicon

### ISSUE THREAD

**Issue by jpfairbanks** [cjhutto/bsd#9]
So the lexicon needs to get shipped when you install this module, but code can't depend on it being in the same place on every machine. Has anyone handling this kind of large file dependency in python before?

**Comment by cjhutto** [comment]
The closest I cam was setting up the local / relative link to the lexicon in my update to vader: see lines 195-200 in my vader repo [code](https://github.com/cjhutto/vaderSentiment/blob/master/vaderSentiment/vaderSentiment.py).

**Comment by jpfairbanks** [comment]
I found out about this argument`package_data={'bsdetector': ['*.json']}` in #10
